### PR TITLE
ENH: Separate anat/func results from connectivity

### PR DESCRIPTION
**Pull request by effigies**
This demonstrates the use of `DatasetLinks`/BIDS-URIs to refer to files across dataset boundaries.

### CODE REVIEW

**Comment by poldrack** [comment]
thanks for this - one concern is that this sort of implies that atlases should go into the anat folder - in this case that's true, but in general they might also be functionally derived (or derived using a combination of modalities). It seems like having a separate atlas folder would be preferable to having atlases strewn around depending on their derivation. @jdkent might have thoughts as well.

**Comment by jdkent** [comment]
I'm inclined to let atlas data (niftis/giftis, etc.) live where they are derived with either a sidecar pointing to the `_dseg.tsv` describing what the values in the data file represent, or perhaps using inheritance if the `_dseg.tsv` lives at the root of the dataset perhaps in a atlas directory.

**Comment by effigies** [comment]
Ah, this wasn't intended to be normative about where all atlases should be placed. This just supposes that these ones are where they are, and shows how to link to them.

**Comment by poldrack** [comment]
got it, thanks!

**Pull request merged**
